module Dom3
	class ConstData
		NATIONS = {
			"EA"=> {0 => "Arcoscephale",
					1 => "Ermor",
					2 => "Ulm",
					3 => "Marverni",
					4 => "Sauromatia",
					5 => "T'ien Ch'i",
					7 => "Mictlan",
					8 => "Abysia",
					9 => "Caelum",
					10 => "C'tis",
					11 => "Pangaea",
					12 => "Agartha",
					13 => "Tir na n'Og",
					14 => "Fomoria",
					15 => "Vanheim",
					16 => "Helheim",
					17 => "Niefelheim",
					18 => "Kailasa",
					19 => "Yomi",
					20 => "Hinnom",
					21 => "Atlantis",
					22 => "R'lyeh",
					26 => "Oceania",
					68 => "Lanka" 
					},

			"MA"=> {27 => "Arcoscephale",
					28 => "Ermor",
					29 => "Pythium",
					30 => "Man",
					31 => "Ulm",
					32 => "Marignon",
					33 => "Mictlan",
					34 => "T'ien Ch'i",
					35 => "Machaka",
					36 => "Agartha",
					37 => "Abysia",
					38 => "Caelum",
					39 => "C'tis",
					40 => "Pangaea",
					41 => "Vanheim",
					42 => "Jotunheim",
					43 => "Bandar Log",
					44 => "Shinuyama",
					45 => "Ashdod",
					46 => "Atlantis",
					47 => "R'lyeh",
					48 => "Oceania",
					69 => "Eriu"
					},

			"LA"=> {49 => "Arcoscephale",
					50 => "Ermor",
					51 => "Man",
					52 => "Ulm",
					53 => "Marignon",
					54 => "Mictlan",
					55 => "T'ien Ch'i",
					56 => "Jomon",
					57 => "Agartha",
					58 => "Abysia",
					59 => "Caelum",
					60 => "C'tis",
					61 => "Pangaea",
					62 => "Midgard",
					63 => "Utgard",
					64 => "Patala",
					65 => "Gath",
					66 => "Atlantis",
					67 => "R'lyeh",
					70 => "Pythium",
					71 => "Bogarus"
					},
			"Other" => {}
		}
		ADMINS = [
			'brainwrinkle@gmail.com'
		]
	end
end

module Dom4
	class ConstData
		NATIONS = {
			"EA"=> {5 => "Arcoscephale",
					6 => "Ermor",
					7 => "Ulm",
					8 => "Marverni",
					9 => "Sauromatia",
					10 => "T'ien Ch'i",
					11 => "Machaka",
					12 => "Mictlan",
					13 => "Abysia",
					14 => "Caelum",
					15 => "C'tis",
					16 => "Pangaea",
					17 => "Agartha",
					18 => "Tir na n'Og",
					19 => "Fomoria",
					20 => "Vanheim",
					21 => "Helheim",
					22 => "Niefelheim",
					25 => "Kailasa",
					26 => "Lanka", 
					27 => "Yomi",
					28 => "Hinnom",
					29 => "Ur",
					30 => "Berytos",
					83 => "Atlantis",
					84 => "R'lyeh",
					85 => "Pelagia",
					86 => "Oceania"
					},

			"MA"=> {33 => "Arcoscephale",
					34 => "Ermor",
					35 => "Sceleria",
					36 => "Pythium",
					37 => "Man",
					38 => "Eriu",
					39 => "Ulm",
					40 => "Marignon",
					41 => "Mictlan",
					42 => "T'ien Ch'i",
					43 => "Machaka",
					44 => "Agartha",
					45 => "Abysia",
					46 => "Caelum",
					47 => "C'tis",
					48 => "Pangaea",
					49 => "Asphodel",
					50 => "Vanheim",
					51 => "Jotunheim",
					52 => "Vanarus",
					53 => "Bandar Log",
					54 => "Shinuyama",
					55 => "Ashdod",
					87 => "Atlantis",
					88 => "R'lyeh",
					89 => "Pelagia",
					90 => "Oceania"
					},

			"LA"=> {60 => "Arcoscephale",
					61 => "Pythium",
					62 => "Lemuria",
					63 => "Man",
					64 => "Ulm",
					65 => "Marignon",
					66 => "Mictlan",
					67 => "T'ien Ch'i",
					68 => "Jomon",
					69 => "Agartha",
					71 => "Abysia",
					72 => "Caelum",
					73 => "C'tis",
					74 => "Pangaea",
					75 => "Midgard",
					76 => "Utgard",
					77 => "Bogarus",
					78 => "Patala",
					79 => "Gath",
					91 => "Atlantis",
					92 => "R'lyeh"
					},
			"Other" => {}
		}
		ADMINS = [
			'brainwrinkle@gmail.com'
		]
	end
end