module Dom3
	class ConstData
		NATIONS = {
			"EA"=> {0 => "Arcoscephale",
					1 => "Ermor",
					2 => "Ulm",
					3 => "Marverni",
					4 => "Sauromatia",
					5 => "T'ien Ch'i",
					6 => "Machaka", 
					7 => "Mictlan",
					8 => "Abysia",
					9 => "Caelum",
					10 => "C'tis",
					11 => "Pangaea",
					12 => "Agartha",
					13 => "Tir na n'Og",
					14 => "Fomoria",
					15 => "Vanheim",
					16 => "Helheim",
					17 => "Niefelheim",
					18 => "Kailasa",
					19 => "Yomi",
					20 => "Hinnom",
					21 => "Atlantis",
					22 => "R'lyeh",
					26 => "Oceania",
					68 => "Lanka" 
					},

			"MA"=> {27 => "Arcoscephale",
					28 => "Ermor",
					29 => "Pythium",
					30 => "Man",
					31 => "Ulm",
					32 => "Marignon",
					33 => "Mictlan",
					34 => "T'ien Ch'i",
					35 => "Machaka",
					36 => "Agartha",
					37 => "Abysia",
					38 => "Caelum",
					39 => "C'tis",
					40 => "Pangaea",
					41 => "Vanheim",
					42 => "Jotunheim",
					43 => "Bandar Log",
					44 => "Shinuyama",
					45 => "Ashdod",
					46 => "Atlantis",
					47 => "R'lyeh",
					48 => "Oceania",
					69 => "Eriu"
					},

			"LA"=> {49 => "Arcoscephale",
					50 => "Ermor",
					51 => "Man",
					52 => "Ulm",
					53 => "Marignon",
					54 => "Mictlan",
					55 => "T'ien Ch'i",
					56 => "Jomon",
					57 => "Agartha",
					58 => "Abysia",
					59 => "Caelum",
					60 => "C'tis",
					61 => "Pangaea",
					62 => "Midgard",
					63 => "Utgard",
					64 => "Patala",
					65 => "Gath",
					66 => "Atlantis",
					67 => "R'lyeh",
					70 => "Pythium",
					71 => "Bogarus",
					72 => "Machaka"
					},
			"Other" => {
				#EA
					0 => "EA Arcoscephale",
					1 => "EA Ermor",
					2 => "EA Ulm",
					3 => "EA Marverni",
					4 => "EA Sauromatia",
					5 => "EA T'ien Ch'i",
					7 => "EA Mictlan",
					6 => "EA Machaka", 
					8 => "EA Abysia",
					9 => "EA Caelum",
					10 => "EA C'tis",
					11 => "EA Pangaea",
					12 => "EA Agartha",
					13 => "EA Tir na n'Og",
					14 => "EA Fomoria",
					15 => "EA Vanheim",
					16 => "EA Helheim",
					17 => "EA Niefelheim",
					18 => "EA Kailasa",
					19 => "EA Yomi",
					20 => "EA Hinnom",
					21 => "EA Atlantis",
					22 => "EA R'lyeh",
					26 => "EA Oceania",
					68 => "EA Lanka" ,
				#MA
					27 => "MA Arcoscephale",
					28 => "MA Ermor",
					29 => "MA Pythium",
					30 => "MA Man",
					31 => "MA Ulm",
					32 => "MA Marignon",
					33 => "MA Mictlan",
					34 => "MA T'ien Ch'i",
					35 => "MA Machaka",
					36 => "MA Agartha",
					37 => "MA Abysia",
					38 => "MA Caelum",
					39 => "MA C'tis",
					40 => "MA Pangaea",
					41 => "MA Vanheim",
					42 => "MA Jotunheim",
					43 => "MA Bandar Log",
					44 => "MA Shinuyama",
					45 => "MA Ashdod",
					46 => "MA Atlantis",
					47 => "MA R'lyeh",
					48 => "MA Oceania",
					69 => "MA Eriu",
				#LA
					49 => "LA Arcoscephale",
					50 => "LA Ermor",
					51 => "LA Man",
					52 => "LA Ulm",
					53 => "LA Marignon",
					54 => "LA Mictlan",
					55 => "LA T'ien Ch'i",
					56 => "LA Jomon",
					57 => "LA Agartha",
					58 => "LA Abysia",
					59 => "LA Caelum",
					60 => "LA C'tis",
					61 => "LA Pangaea",
					62 => "LA Midgard",
					63 => "LA Utgard",
					64 => "LA Patala",
					65 => "LA Gath",
					66 => "LA Atlantis",
					67 => "LA R'lyeh",
					70 => "LA Pythium",
					71 => "LA Bogarus",
					72 => "LA Machaka"
			}
		}
		ADMINS = [
			'brainwrinkle@gmail.com'
		]
	end
end