NATIONS = {
			"EA"=> {"0" => "Arcoscephale",
					"1" => "Ermor",
					"2" => "Ulm",
					"3" => "Marverni",
					"4" => "Sauromatia",
					"5" => "T'ien Ch'i",
					"7" => "Mictlan",
					"8" => "Abysia",
					"9" => "Caelum",
					"10" => "C'tis",
					"11" => "Pangaea",
					"12" => "Agartha",
					"13" => "Tir na n'Og",
					"14" => "Fomoria",
					"15" => "Vanheim",
					"16" => "Helheim",
					"17" => "Niefelheim",
					"18" => "Kailasa",
					"19" => "Yomi",
					"20" => "Hinnom",
					"21" => "Atlantis",
					"22" => "R'lyeh",
					"26" => "Oceania",
					"68" => "Lanka" 
					},

			"MA"=> {"27" => "Arcoscephale",
					"28" => "Ermor",
					"29" => "Pythium",
					"30" => "Man",
					"31" => "Ulm",
					"32" => "Marignon",
					"33" => "Mictlan",
					"34" => "T'ien Ch'i",
					"35" => "Machaka",
					"36" => "Agartha",
					"37" => "Abysia",
					"38" => "Caelum",
					"39" => "C'tis",
					"40" => "Pangaea",
					"41" => "Vanheim",
					"42" => "Jotunheim",
					"43" => "Bandar Log",
					"44" => "Shinuyama",
					"45" => "Ashdod",
					"46" => "Atlantis",
					"47" => "R'lyeh",
					"48" => "Oceania",
					"69" => "Eriu"
					},

			"LA"=> {"49" => "Arcoscephale",
					"50" => "Ermor",
					"51" => "Man",
					"52" => "Ulm",
					"53" => "Marignon",
					"54" => "Mictlan",
					"55" => "T'ien Ch'i",
					"56" => "Jomon",
					"57" => "Agartha",
					"58" => "Abysia",
					"59" => "Caelum",
					"60" => "C'tis",
					"61" => "Pangaea",
					"62" => "Midgard",
					"63" => "Utgard",
					"64" => "Patala",
					"65" => "Gath",
					"66" => "Atlantis",
					"67" => "R'lyeh",
					"70" => "Pythium",
					"71" => "Bogarus"
					},
			"Other" => {}
		}